services:
  redis:
    image: "redis:${REDIS_VERSION}"
    container_name: redis
    platform:
      linux/arm64
    # linux/amd64 # For production
    networks:
      - local-network
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --bind ${REDIS_BIND}
      --port ${REDIS_INTERNAL_PORT}
      --requirepass ${REDIS_PASSWORD}
      --save ${REDIS_SAVE_POLICY}
      --loglevel ${REDIS_LOGLEVEL}
      --maxmemory-policy ${REDIS_MAXMEMORY_POLICY}
      --appendonly ${REDIS_APPENDONLY}
      --appendfsync ${REDIS_APPENDFSYNC}
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USERNAME: default
    ports:
      - "${REDIS_PORT}:${REDIS_INTERNAL_PORT}"
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf


networks:
  local-network:
    external: true